name: build-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release/tag version'     
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package -DnewVersion=${{ github.event.repository.name }}-${{ github.event.inputs.version }}-RELEASE
      
    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}-${{ github.event.inputs.version }}-RELEASE
        path: |
          **/*.jar
      
    - name: Generate Token
      id: ghapp-token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_PEM }}

    - name: Create Release
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: create-release
        token: ${{ steps.ghapp-token.outputs.token }}
        inputs: '{ "version": "${{ github.event.inputs.version }}" }'
