name: build-snapshot

# build on any branch that is not default and deploy to staging
on:
  push:
    branches:    
      - '*'
      - '!main' # update to default branch'

  workflow_dispatch:

jobs:
  build:
    environment: development
    runs-on: ubuntu-latest
    
    # checkout
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    # build maven
    - run: mvn -B install -file pom.xml
    
    # generate token for workflow-dispatch
    - name: Generate Token
      id: ghapp-token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_PEM }}

    # invoke deployment to development environment
    - name: Deploy Development
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: deploy-development
        token: ${{ steps.ghapp-token.outputs.token }}
