name: build-snapshot

on:
  push:
    branches:    
      - '*'
      - '!main'

jobs:
  build:
    environment: development
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    - run: mvn -B install -file pom.xml
    
    - name: Generate Token
      id: ghapp-token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_PEM }}

    - name: Deploy Development
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: deploy-development
        token: ${{ steps.ghapp-token.outputs.token }}
