name: build-master

# when a change lands on the default branch, perform a build to validate the commit
on:
  push:
    branches:    
      - 'main' # update to default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout code base
    - uses: actions/checkout@v2
    # run maven
    - run: mvn -B install -file pom.xml
