name: maven-build-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release/tag version'     
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package -DnewVersion=${{ github.event.repository.name }}-${{ github.event.inputs.version }}-RELEASE
