name: deploy-staging

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release/tag version'     
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    environment: staging
    steps:
      - name: deploy to staging environment
        run: |
          echo "deploying staging"
          
  invoke-production-deploy:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    needs: deploy
    steps:
    - name: Generate Token
      id: ghapp-token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_PEM }}

    - name: Deploy Staging
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: deploy-production
        token: ${{ steps.ghapp-token.outputs.token }}
        inputs: '{ "version": "${{ github.event.inputs.version }}" }'
