name: deploy-production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release/tag version'     
        required: true
        default: ''

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    environment: production
    steps:
      - name: deploy to production environment
        run: |
          echo "deploying production"

  merge-default-branch:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps: 
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: merge
      uses: devmasx/merge-branch@master
      with:
        type: now
        target_branch: main
        github_token: ${{ github.token }}
