name: deploy-development

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: deploy to development environment
        run: |
          echo "deploying development"
