name: deploy-production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release/tag version'     
        required: true
        default: ''

jobs:
  deploy-production:
    runs-on: ubuntu-latest # update to self-hosted runner
    if: github.ref != 'refs/heads/main' # update default branch
    # uses production environment approval process
    environment: production
    steps:
      - name: deploy to production environment
        # TODO: add steps
        run: |
          echo "deploying production"
