name: maven-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release/tag version'     
        required: true
        default: ''

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package -DnewVersion=${{ github.event.repository.name }}-${{ github.event.inputs.version }}-RELEASE
      
    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v2.4.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Tag
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.inputs.version }}

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: ${{ github.event.inputs.version }}
        body: ${{steps.build_changelog.outputs.changelog}}

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}-${{ github.event.inputs.version }}-RELEASE
        path: |
          **/*.jar
  
    - name: Update POM
      run: |
        sed -e s/${{ github.event.inputs.version }}-RELEASE/${{ github.event.inputs.version }}-SNAPSHOT/g
      
    - name: Commit POM
      run: |
        git config --global user.name 'pom-bot'
        git config --global user.email 'pom-bot@cadence.com'
        git stash
        git checkout main
        git stash ${GITHUB_REF##*/}
        git add pom.xml
        git commit -am "Update POM version to ${{ github.event.inputs.version }}-SNAPSHOT"
        git push

