name: maven-update-pom
on: [create]
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: casa-vega/simple-java-maven-app-original
          releases-only: true
        id: pom
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: update pom
        run: mvn versions:set -DnewVersion=${{ steps.pom.outputs.tag }}-SNAPSHOT
      - name: commit pom
        run: |
          git config --global user.name 'pom-bot'
          git config --global user.email 'pom-bot@cadence.com'
          git add pom.xml
          git commit -am "Update POM version to ${{ steps.pom.outputs.tag }}-SNAPSHOT"
          git push
